"""empty message

Revision ID: caa7248f6929
Revises: 
Create Date: 2024-10-08 18:47:12.489429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa7248f6929'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_hashed_accessCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('childsClass', sa.String(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fullName')
    )
    op.create_table('months_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('fk_month_school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_month_school_id'], ['schools_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_school_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools_table.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools_table.id'], name='fk_school_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='fk_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'school_id')
    )
    op.create_table('shifts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('startTime', sa.String(), nullable=False),
    sa.Column('endTime', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts_table')
    op.drop_table('user_school_association')
    op.drop_table('months_table')
    op.drop_table('users_table')
    op.drop_table('schools_table')
    # ### end Alembic commands ###
