"""empty message

Revision ID: daaa87982d10
Revises: caa7248f6929
Create Date: 2024-10-15 15:15:02.597847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaa87982d10'
down_revision = 'caa7248f6929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('childsClass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('childsClass', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
